### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by RootLUG** [RootLUG/aura#1]
Are interested in collaborating with open source community but you are not a developer? Fear not, we have several other ways to you can contribute. This project is looking for someone who can design the logo of the Aura security framework/project.

I'm currently in the process of creating the project websites and for these, a logo is needed. (I really suck at graphics) Aside from having a good feeling of contributing to the open source community, isn't that a great way to bump things up in your CV?

**Comment by mirzazulfan** [comment]
Hi @RootLUG I've designed a logo for you, what dou you think? if you have an idea please share with me, it would be better for me. Reagard!
![aura](https://user-images.githubusercontent.com/36124339/59248570-0245a580-8c4d-11e9-8d21-32a4cb1283af.png)

**Comment by RootLUG** [comment]
Hello @mirzazulfan ,
Thank you for your contribution, the logo looks awesome.
Regarding the ideas, I noticed that the "lock" in the middle has an outline that probably would not be visible when scaled down. Most likely this logo would be used in different sizes, apart from high resolution at project homepage also most likely something like 64x64 or similar as an icon; both agains black & white backrounds.
I think, regarding the colors it's all god and easily convertible into black or white variation. I'm more now loudly brainstorming how it would look like when scaled to so it's still recognizable even when small.
I really love this, what are your thought on that scaling?

**Comment by mirzazulfan** [comment]
Thanks for your response @RootLUG , what about this size? if it's still not suitable, I will try again well.
![size](https://user-images.githubusercontent.com/36124339/59405079-6c885280-8dd3-11e9-8946-dc7cbef18b5d.png)

**Comment by RootLUG** [comment]
@mirzazulfan Yes, I think it is perfect right now. The first one in a list is great to be recognizable even in small dimensions (64px); or we can keep the variations you presented and use them based on the use case (where it's going to be used and how big).

From my side, I think it's now in a ready to use state. What' the format of the logo files? Could you export it for example to SVG so I can add it to the repository? Or PSD so I can convert it into a scalable format.
Also, if it's ok by you, I will add you to the list of contributors as I appreciate the time you took to design this. Thank you!

**Comment by mirzazulfan** [comment]
I uploaded all files. .svg .png .ai. and .psd #4 . Best regard!

**Comment by RootLUG** [comment]
Great, I merged the pull request and move logos to different folder + added you to contributors already and logo on the README.md as a header.
Just one more question before closing this task, what is the font used for the text in the `logotype.png` format?

**Comment by mirzazulfan** [comment]
Sorry for late reply, I used Square721 BT for font.
